### ISSUE TITLE
Running Example using "nodejs12.x" - can't launch Browser 

### ISSUE THREAD

**Issue by munderseth** [shubhamsc/taiko-serverless-chrome#2]
Hi @shubhamsc, @BugDiver first thanks for the example. This is more of a question -- have you tried this example recently?

We use Taiko for UI testing within a GitHub Workspace. I wanted to consider switching over our UI testing to leverage AWS Lambdas, thus your example is helpful 👍. 

When using `serverless deploy -v` the runtime requires being updated. 
<pre>
An error occurred: TaikoDashtestLambdaFunction - The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions.
</pre> 

I went ahead a modified the `serverless.yaml` to `nodejs12.x`.  

I also had to update the *serverless-plugin-chrome* to use the latest version (`-55.3`). 
<pre>
"dependencies": {
    "@serverless-chrome/lambda": "^1.0.0-55",
    "serverless-plugin-chrome": "^1.0.0-55.3",
    "taiko": "^0.8.0"
  },
  "devDependencies": {
    "chrome-launcher": "^0.10.7"
  }
</pre>

Once I did these modifications I was able to deploy. 

When `invoking` I am **unable** to start Chrome:
<pre>
2020-02-11T23:41:56.295Z	e3b182fb-a462-4ab1-a720-6f00875396d7	ERROR	Error: Unable to start Chrome. If you have the DEBUG env variable set,there will be more in the logs.
    at /var/task/node_modules/@serverless-chrome/lambda/dist/bundle.cjs.js:376:13
    at Generator.throw (<anonymous>)
    at step (/var/task/node_modules/@serverless-chrome/lambda/dist/bundle.cjs.js:311:193)
    at /var/task/node_modules/@serverless-chrome/lambda/dist/bundle.cjs.js:311:404
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
2020-02-11T23:41:56.297Z	e3b182fb-a462-4ab1-a720-6f00875396d7	ERROR	Invoke Error 	
{
    "errorType": "Error",
    "errorMessage": "Browser or page not initialized. Call `openBrowser()` before using this API",
    "stack": [
        "Error: Browser or page not initialized. Call `openBrowser()` before using this API",
        "    at validate (/var/task/node_modules/taiko/lib/taiko.js:2786:30)",
        "    at module.exports.closeBrowser (/var/task/node_modules/taiko/lib/taiko.js:212:5)",
        "    at module.exports.<computed> (/var/task/node_modules/taiko/lib/taiko.js:2885:42)",
        "    at Runtime.module.exports.handler (/var/task/taiko-test.js:18:15)",
        "    at processTicksAndRejections (internal/process/task_queues.js:94:5)"
    ]
}
</pre>

Do you have any suggestions on how I should pursue this? I don't think/believe this is a Taiko issue.  Any suggestions are much appreciated.

**Comment by munderseth** [comment]
I believe this [Issue](https://github.com/adieuadieu/serverless-chrome/issues/251) is the cause, thus closing.
